apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort
  selector:
    app: primeiro-pod #bound desse serviço com este pod
  ports:
    - port: 8080
      nodePort: 30000 #30000-32767