apiVersion: v1
kind: Service
metadata:
  name: svc-sistema-de-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort:80 #por padrão
      nodePort: 30002 #não sendo informado será escolhida uma porta aleatória
  selector:
    app: sistema-de-noticias