apiVersion: v1
kind: Service
metadata:
  name: svc-portal-de-noticias
spec:
  type: NodePort
  ports:
    - port: 80
      #targetPort:80 #por padrão
      nodePort: 30001 #não sendo informado será escolhida uma porta aleatória
  selector:
    app: portal-de-noticias